### ISSUE TITLE
This plugin is not working ,kindly update it 

### ISSUE THREAD

**Issue by mdasad0** [acasado86/qr-user-login#1]
hello sir, it is very useful plugin but it is not working, please sir please i request you please update it,

**Comment by acasado86** [comment]
Hi mdasad0,

I checked the plugin in WordPress 4.9.5 and it worked fine.

The plugin needs that you configured all the roles who can login via QR and assign the role to the users.
Users > QR Login Capability

After that, the QR image is generate on the user profile setting page.

Other you must know is that plugin use Google API Chart (the server must have access to Internet): https://chart.googleapis.com/chart 

Bye,

**Comment by mdasad0** [comment]
sir , lots of thanks to reply , 
i would like to ask you that , how to scan this QR code , where it can be scan 
when i goto my login page i do not find any webcam scanning option ,, where  i can scan this ??

**Comment by acasado86** [comment]
Hi, you must use a external app for scan the code (for example
https://play.google.com/store/apps/details?id=tw.mobileapp.qrcode.banner&hl=es
).

When I design the plugin, I think on put the QR code on wedding invitations
(to help users to login on the website).

The use that you want to do is different, maybe you can to combine with
other plugin on WordPress or use other software to read the QR on the
computer.

Attentively,
acasado86

**Comment by acasado86** [comment]
Hi again,
I finded next URLs. I think may be useful for you.
https://webqr.com/
https://atandrastoth.co.uk/main/pages/plugins/webcodecamjs/


Good luck,
